### ISSUE TITLE
capturing any descriptor

### ISSUE THREAD

**Issue by zoggy** [sylvarant/captureio#1]
Hello,

Do you plan do add functions in the interface to allow capturing any file descriptor ?

**Comment by sylvarant** [comment]
I can add that.
Though the way the library works right now, means that the output is diverted to your capture 
and thus won't end up in the descriptor, unless you pump it in there afterwards.
Is that what you're interested in ?

**Comment by zoggy** [comment]
Yes. Thanks!

**Comment by sylvarant** [comment]
I have added it in captureio 0.1.2, for an example see the ReadMe.
Might take a little until opam is updated with 0.1.2 though.
